# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94842b2ec34a21e4b0521484709629db5800b9a6f72731900fc9a670b910bb367a39a0135ad7d584376c6435b08421c7e201ce4ad1595f503394785881585ea1

test:
  secret_key_base: eba745767c5ec45c0b25b5ddac5947cd92e597c1e516b23b344b2e075763650d0dc3fc77c99f16c9150420589667a51ed601f3da9959ebfb6e0a653ea1c429c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
